title:  AI Book
description:  The first Smart AI company that we help customers based on  face recognition and background to expand your knowledge and skills
show_downloads: false

baseurl: "/AI Book" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://www.aibook.io" # 

AI Book:
  date_format: "%b %-d, %Y"

```
gems:
  - jekyll-feed
```
gems:
  - jekyll-seo-tag

theme: # leave it empty


twitter:
  username: Aibook2017
#  site:
facebook:
  #publisher: AIbook2017
#  admins:
